import random
import time
import copy
import math
import numpy as np
from typing import List, Tuple, Dict
from collections import defaultdict

from ..core.problem import Problem
from ..core.solution import Solution, Route
from ..core.eval import evaluate

class DFASolver:
    def __init__(self, problem: Problem, seed: int = 42, evaluator=evaluate, **kwargs):
        self.prob = problem
        self.evaluator = evaluator
        self.rng = random.Random(seed)
        
        self.pop_size = kwargs.get("pop_size", 100) 
        self.gamma = kwargs.get("gamma", 0.95)    
        self.max_generation = kwargs.get("max_generation", 500)
        
    def _hamming_distance(self, sol1: Solution, sol2: Solution) -> int:
        """
        Tính khoảng cách Hamming giữa hai cá thể.
        So sánh thứ tự khách hàng trong chuỗi lộ trình phẳng.
        """
        seq1 = [node for r in sol1.routes for node in r.seq[1:-1]]
        seq2 = [node for r in sol2.routes for node in r.seq[1:-1]]
        
        dist = 0
        for n1, n2 in zip(seq1, seq2):
            if n1 != n2:
                dist += 1
        dist += abs(len(seq1) - len(seq2)) # Tính phần chênh lệch độ dài [cite: 981]
        return dist

    def _fast_insertion(self, routes: List[Route]) -> List[Route]:
        """
        Optimal insertion operator: Only insert one node from a route to another route.
        """
        new_routes = [copy.copy(r) for r in routes]
        valid_idxs = [i for i, r in enumerate(new_routes) if len(r.seq) > 2]
        if not valid_idxs: return routes
            
        src_idx = self.rng.choice(valid_idxs)
        new_routes[src_idx] = copy.deepcopy(new_routes[src_idx])
        node_idx = self.rng.randint(1, len(new_routes[src_idx].seq) - 2)
        node_id = new_routes[src_idx].seq.pop(node_idx)
        
        # Insert node into another route
        dst_idx = self.rng.randint(0, len(new_routes) - 1)
        if dst_idx != src_idx:
            new_routes[dst_idx] = copy.deepcopy(new_routes[dst_idx])
        
        insert_pos = self.rng.randint(1, len(new_routes[dst_idx].seq) - 1)
        new_routes[dst_idx].seq.insert(insert_pos, node_id)
        
        return new_routes

    def _move_firefly(self, x_i: Solution, x_j: Solution, i_cost: float, iteration: int) -> Solution:
        """
        Firefly movement strategy:
        Move firefly x_i towards x_j based on their attractiveness (cost).
        """
        # Hamming distance
        r_ij = self._hamming_distance(x_i, x_j)
        if r_ij <= 1: 
            return x_i
            
        # Calculate number of candidates to generate
        upper_limit = max(2, int(r_ij * (self.gamma ** iteration)))
        n = self.rng.randint(2, upper_limit) 
        
        best_sol = x_i
        best_cost = i_cost
        
        # Candidate are generated by insertion and route transfer
        for _ in range(n):
            if self.rng.random() < 0.7:
                temp_routes = self._fast_insertion(x_i.routes)
            else:
                temp_routes = self._transfer_route_operator(x_i.routes)
            
            temp_sol = Solution(routes=temp_routes)
            temp_cost, _ = self.evaluator(self.prob, temp_sol)
            
            if temp_cost < best_cost:
                best_cost = temp_cost
                best_sol = temp_sol
                
        return best_sol

    def _transfer_route_operator(self, routes: List[Route]) -> List[Route]:
        """
        Route Transfer Operator: Change the vehicle assigned to a route.
        """
        new_routes = [copy.copy(r) for r in routes]
        if not new_routes: return routes
        
        # Randomly select a route to change vehicle
        valid_idxs = [i for i, r in enumerate(new_routes) if len(r.seq) > 2]
        if not valid_idxs: return routes
        
        target_route_idx = self.rng.choice(valid_idxs)
        route_to_move = copy.copy(new_routes[target_route_idx])
        
        # Collect goods types in the route
        route_goods = set()
        for nid in route_to_move.seq[1:-1]:
            cust = self.prob.nodes_map.get(nid)
            if cust:
                for o in cust.order_list:
                    for it in o.good_list:
                        route_goods.add(it.type)
        
        # List eligible vehicles
        eligible_veh_ids = [
            v.id for v in self.prob.vehicles 
            if route_goods.issubset(v.allowed_good_type) and v.id != route_to_move.vehicle_id
        ]
        
        if eligible_veh_ids:
            # New vehicle assignment
            route_to_move.vehicle_id = self.rng.choice(eligible_veh_ids)
            new_routes[target_route_idx] = route_to_move
            
        return new_routes

    def solve(self, time_limit_sec: float = 60.0) -> Solution:
        t0 = time.time()
        
        pop = self._smart_initialize()
        pop_costs = [self.evaluator(self.prob, s)[0] for s in pop]
        
        best_idx_init = np.argmin(pop_costs)
        global_best_cost = pop_costs[best_idx_init]
        global_best_sol = copy.deepcopy(pop[best_idx_init])
        
        for gen in range(self.max_generation):
            if time.time() - t0 > time_limit_sec: 
                break
            
            num_random_pairs = 5 * self.pop_size
            for _ in range(num_random_pairs):
                i, j = self.rng.sample(range(self.pop_size), 2)
                
                if pop_costs[j] < pop_costs[i]:
                    pop[i] = self._move_firefly(pop[i], pop[j], pop_costs[i], gen)
                    pop_costs[i], _ = self.evaluator(self.prob, pop[i])
                    
                    if pop_costs[i] < global_best_cost:
                        global_best_cost = pop_costs[i]
                        global_best_sol = copy.deepcopy(pop[i])
            
            best_idx = np.argmin(pop_costs)
            pop[best_idx] = Solution(routes=self._fast_insertion(pop[best_idx].routes))
            pop_costs[best_idx], _ = self.evaluator(self.prob, pop[best_idx])
            
            if pop_costs[best_idx] < global_best_cost:
                global_best_cost = pop_costs[best_idx]
                global_best_sol = copy.deepcopy(pop[best_idx])
            
            if gen % 5 == 0:
                print(f"Gen {gen} | Global Best: {global_best_cost:.2f} | Time: {time.time()-t0:.1f}s")
                
        return global_best_sol

    def _smart_initialize(self) -> List[Solution]:
        """
        Smart initialization of population using clustering and route construction.
        """
        P = self.prob
        r = self.rng
        pop: List[Solution] = []
        
        customer_ids = [c.id for c in P.customers]
        all_vehicle_ids = [v.id for v in P.vehicles]
        veh_map = {v.id: v for v in P.vehicles}

        for _ in range(self.pop_size):
            depot_to_customers = defaultdict(list)
            for cid in customer_ids:
                best_depot = min(P.depots, key=lambda d: P.get_distance(d.id, cid))
                depot_to_customers[best_depot.id].append(cid)

            available_routes_data = []
            for d_id, c_list in depot_to_customers.items():
                if not c_list: continue
                
                temp_c_list = c_list[:]
                r.shuffle(temp_c_list)
                
                avg_capacity = sum(v.max_weight for v in P.vehicles) / len(P.vehicles)
                current_route_c = []
                current_w = 0
                
                for cid in temp_c_list:
                    c_weight = sum(o.weight for o in P.nodes_map[cid].order_list)
                    if current_w + c_weight > avg_capacity and current_route_c:
                        available_routes_data.append({'d': d_id, 'c': current_route_c})
                        current_route_c = [cid]
                        current_w = c_weight
                    else:
                        current_route_c.append(cid)
                        current_w += c_weight
                
                if current_route_c:
                    available_routes_data.append({'d': d_id, 'c': current_route_c})

            # Assign routes to vehicles (random assignment to ensure exploration)
            r.shuffle(available_routes_data)
            veh_to_routes = {v_id: [] for v_id in all_vehicle_ids}
            
            for rd_data in available_routes_data:
                # Choose a vehicle randomly that has compatible allowed_good_type
                route_goods = {it.type for cid in rd_data['c'] 
                               for o in P.nodes_map[cid].order_list 
                               for it in o.good_list}
                
                eligible_vehs = [v_id for v_id in all_vehicle_ids 
                                 if route_goods.issubset(veh_map[v_id].allowed_good_type)]
                
                if eligible_vehs:
                    target_v = r.choice(eligible_vehs)
                    veh_to_routes[target_v].append(rd_data)

            # Package into Solution object
            final_routes = []
            for v_id, routes_list in veh_to_routes.items():
                for rd in routes_list:
                    # Format: [Depot, C1, C2, ..., Depot]
                    seq = [rd['d']] + rd['c'] + [rd['d']]
                    final_routes.append(Route(vehicle_id=v_id, seq=seq))
            
            # If a vehicle has no assigned routes, it is not added to the solution
            pop.append(Solution(routes=final_routes))

        return pop
